version: '3.1'

services:

  questionnare_env:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/questionnare:rw

  questionnare_make_migrations:
    extends:
      service: questionnare_env
    command: python manage.py makemigrations

  questionnare_migrate:
    extends:
      service: questionnare_env
    depends_on:
      - questionnare_make_migrations
    command: python manage.py migrate

  createsuperuser:
    extends:
      service: questionnare_env
    depends_on:
      - questionnare_migrate
    command: python manage.py createsuperuser

  runserver:
    extends:
      service: questionnare_env
    command: python manage.py runserver
    ports:
      - 8000:8000
